### DISCUSSION TITLE
how to handle packages in ansible that have custom scripts on install

### DISCUSSION THREAD

**Discussion by jalmillateguiRPA** [geerlingguy/ansible-for-devops#530] [Q&A]
Hi All,

I have been reading the book, and doing my own scripts. I'm automating an install of a software that uses MSSQL 2019 express database on linux and I have managed to build my playbook to add the repository, and install the package. However, the package installer gets stuck waiting for to accept the license.

The system I'm testing this in is a Rocky linux 8 box.

The relevant task in the play book are:

```
   - ansible.builtin.name: add mssql repo part 1
      ansible.builtin.get_url:
        url: https://packages.microsoft.com/config/rhel/8/mssql-server-2019.repo
        dest: /etc/yum.repos.d/mssql-server-2019.repo

    - ansible.builtin.name: add mssql repo part 2
      ansible.builtin.get_url:
        url: https://packages.microsoft.com/config/rhel/8/prod.repo
        dest: /etc/yum.repos.d/msprod.repo

    - ansible.builtin.name: install mssql 2019
      dnf:
        name: mssql-server # This one gives an issue..... how to deal with it....
        state: present

    - ansible.builtin.name: install tools for mssql 2019
      dnf:
        name:
          - mssql-tools # This one gives an issue..... how to deal with it....
          - unixODBC-devel
        state: present
```

The rpm custom script ask the following question on install:

```
The license terms for this product can be downloaded from
https://aka.ms/odbc17eula and found in
/usr/share/doc/msodbcsql17/LICENSE.txt . By entering 'YES',
you indicate that you accept the license terms.

Do you accept the license terms? (Enter YES or NO)
YES

The license terms for this product can be downloaded from
http://go.microsoft.com/fwlink/?LinkId=746949 and found in
/usr/share/doc/mssql-tools/LICENSE.txt . By entering 'YES',
you indicate that you accept the license terms.

Do you accept the license terms? (Enter YES or NO)
YES
```

Do anyone has an idea on how pass a "YES" to answer using ansible or a workaround this situation? 

Best Regards,

Javier Almillategui
