### ISSUE TITLE
Ansible playbook failed due to root privileged permission

### ISSUE THREAD

**Issue by khoi-thinh** [geerlingguy/ansible-for-devops#103]
I have 2 instance EC2 on AWS.
On both servers, i created a "khoi" user, create ssh-keygen and copy this to the other server, give it sudo permission and also changed in visudo .
khoi   ALL=(ALL)       NOPASSWD:ALL

The result is: i can ssh from the first server to 2nd one without using password and vice versa.

The problem is every time i run ansible command, it required me to input password.

Additionally, i have a playbook called first.yml
```
---
- hosts: all
  tasks:
   - name: Install apache
     command: yum install -y httpd httpd-devel
   - name: copy files
     command: >
       cp /home/khoi/get-pip.py /home/khoi/ohgod.py
   - name: start apache, config httpd
     command: service httpd start
   - command: chkconfig httpd on
```

After running: ansible-playbook first.yml and input password, i got this error: 

fatal: [ansible-02]: FAILED! => {"changed": true, "cmd": ["yum", "install", "-y", "httpd", "httpd-devel"], "delta": "0:00:00.154725", "end": "2018-07-27 06:26:14.031516", "msg": "non-zero return code", "rc": 1, "start": "2018-07-27 06:26:13.876791", "stderr": "You need to be root to perform this command.", "stderr_lines": ["You need to be root to perform this command."], "stdout": "Loaded plugins: fastestmirror", "stdout_lines": ["Loaded plugins: fastestmirror"]}

fatal: [localhost]: FAILED! => {"changed": true, "cmd": ["yum", "install", "-y", "httpd", "httpd-devel"], "delta": "0:00:00.190187", "end": "2018-07-27 06:26:14.099748", "msg": "non-zero return code", "rc": 1, "start": "2018-07-27 06:26:13.909561", "stderr": "You need to be root to perform this command.", "stderr_lines": ["You need to be root to perform this command."], "stdout": "Loaded plugins: fastestmirror", "stdout_lines": ["Loaded plugins: fastestmirror"]}

Can you tell me how to fix this issue?
