### ISSUE TITLE
Wrong stat path in Dynamic includes (chapter 6)

### ISSUE THREAD

**Issue by sandipb** [geerlingguy/ansible-for-devops#142]
```yaml
# Include extra tasks file, only if it's present at runtime. 
- name: Check if extra_tasks.yml is present.
  stat: path=extras/extra-tasks.yml
  register: extra_tasks_file
  connection: local

- include_tasks: tasks/extra-tasks.yml
  when: extra_tasks_file.stat.exists
```

The `path` parameter to stat should be `tasks/extra-tasks.yml` and not `extras/extra-tasks.yml`
