### ISSUE TITLE
source and destination inversion - Symlink

### ISSUE THREAD

**Issue by MacFlurry** [geerlingguy/ansible-for-devops#171]
Hello,

 ch. 4 page 72
this task:
```
- name: Create drush bin symlink.
  file:
    src: /opt/drush/drush
    dest: /usr/local/bin/drush
    state: link
```
and page 73
it's noted:
> Finally, we create a symlink from /usr/local/bin/drush to the executable at /opt/drush/drush, so we can call the drush command anywhere on the system.

Shouldn't it be from `/opt/drush/drush` to `/usr/local/bin/drush`?

I'm sorry if I was wrong.

Sincerely,

MacFlurry
