### ISSUE TITLE
PHP role usage on Debian Buster in Chapter 6 may need update

### ISSUE THREAD

**Issue by geerlingguy** [geerlingguy/ansible-for-devops#187]
From this issue: https://github.com/geerlingguy/ansible-role-php/issues/281

@luisnabais said:

> Maybe it should be updated/corrected on the Ansible for Devops book, on page "142", Chapter 6 - Playbook Organization - Roles, Includes, and Imports.

Regarding the example in a `debian10` Vagrant Box, he got the error:

```
TASK [geerlingguy.php : Ensure PHP packages are installed.] ************************************************************************************************************************************************
fatal: [debian]: FAILED! => {"changed": false, "msg": "No package matching 'php7.0-common' is available"}
```

**Comment by geerlingguy** [comment]
I'm assuming the example is related to:

```yaml
---
- hosts: all
  become: yes

  roles:
    - geerlingguy.mysql
    - geerlingguy.apache
    - geerlingguy.php
    - geerlingguy.php-mysql
```
