### ISSUE TITLE
playbook in drupal is not idempotent

### ISSUE THREAD

**Issue by arashpath** [geerlingguy/ansible-for-devops#192]
Last task in the `playbook.yml` of `drupal` id not idempotent when you open the website 
and run the playbook again.

```yml
  - name: Set permissions properly on files directory.
    file:
      path: "{{ drupal_core_path }}/sites/default/files"
      mode: 0777
      state: directory
      recurse: yes
```
