### ISSUE TITLE
Node js forever doesn't install properly

### ISSUE THREAD

**Issue by sweyrick** [geerlingguy/ansible-for-devops#23]
When I run the node js example, forever doesn't properly install.  Vagrant 1.8.1/ansible 2.0.0.2

TASK [Check list of running Node.js apps.] *************************************
fatal: [192.168.60.7]: FAILED! => {"changed": false, "cmd": "forever list", "failed": true, "invocation": {"module_args": {"_raw_params": "forever list", "_uses_shell": false, "chdir": null, "creates": null, "executable": null, "removes": null, "warn": true}, "module_name": "command"}, "msg": "[Errno 2] No such file or directory", "rc": 2}

I updated the forever installation to use the command module instead of npm and it works properly.
- name: Install Forever (to run our Node.js app).
    command: "npm install forever -g"

![screen shot 2016-01-27 at 9 09 11 pm](https://cloud.githubusercontent.com/assets/458371/12635633/3c8d3be6-c53a-11e5-81b2-4560261d21b0.png)

**Comment by geerlingguy** [comment]
As a note, I hit this issue as well a while back, but it seems like it was working again last time I checked. I'll try to test again and see if it's still an issue.

**Comment by geerlingguy** [comment]
This is an Ansible core bug, but the workaround is to install `npm` modules using `state=present` instead of `latest`, and if needed, add a separate task that sets `state=latest`.

**Comment by geerlingguy** [comment]
See above commit for the fix.

**Comment by BrunoDuarte** [comment]
Very useful your tip geerlingguy. Thank you!

**Comment by grhawk** [comment]
Hi, very nice work with the books and the videos!!! :)

I am writing here because I am having this same issue while following the book. Below is the ansible playbook I wrote (which looks really similar)

playbook.yml

```yaml
- hosts: all
  become: yes

  vars:
    node_apps_location: /usr/local/opt/node

  tasks:
    - name: Install EPEL repo
      yum: name=epel-release state=present

    # - name: Install Remi gpg key
    #   rpm_key:
    #     key: "https://rpms.remirepo.net/RPM-GPG-KEY-remi"
    #     state: present

    # - name: Install Remi repo.
    #   yum:
    #     name: "https://rpms.remirepo.net/enterprise/remi-release-7.rpm"
    #     state: present

    - name: Ensure firewalld is stopped (only testing here).
      service: name=firewalld state=stopped

    - name: Install Node.js and npm.
      yum: name=npm state=present enablerepo=epel

    - name: Install Forever (to run our Node.js app).
      npm: name=forever global=yes state=present

    - name: Ensure Node.js app folder exists.
      file: "path={{ node_apps_location }} state=directory"

    - name: Copy example Node.js app to server
      copy: "src=app dest={{ node_apps_location }}"

    - name: Install app dependencies defined in package.json.
      npm: path={{ node_apps_location}}/app

    - name: Check list of running Node.js apps.
      command: forever list
      register: forever_list
      changed_when: false

    - name: start example Node.js app.
      command: "forever start {{ node_apps_location }}/app/app.js"
      when: "forever_list.stdout.find(node_apps_location + '/app/app.js') == -1"
```

(yes, the remi stuff also generate some errors, but I am not an expert of RH stuff so I just commented it since does not look important for this specific playbook). 

The error I am getting is:
```
TASK [Check list of running Node.js apps.] *************************************************************************************************************************************************************************************************************************************
fatal: [192.168.60.5]: FAILED! => {"changed": false, "cmd": "forever list", "msg": "[Errno 2] No such file or directory: b'forever': b'forever'", "rc": 2, "stderr": "", "stderr_lines": [], "stdout": "", "stdout_lines": []}
```

If I ssh to the VM I can run forever without problems, so I think this is an installation issue.

Happy to provide more details...
