### ISSUE TITLE
[section_request] Writing custom plugins (tests, filters, modules, etc.)

### ISSUE THREAD

**Issue by geerlingguy** [geerlingguy/ansible-for-devops#243]
I think at a very basic level, going over how to write a plugin would be helpful. For example, the most basic thing:

First, create a new playbook in a project directory.

Then, create `test_plugins/blue.py`:

```python
# blue Ansible test plugin definition.

def is_blue(string):
    blue_values = ['blue', '#0000ff', '#00f', 'rgb(0,0,255)']
    if string in blue_values:
      return True
    else:
      return False

class TestModule(object):
    ''' custom playbook jinja2 tests '''

    def tests(self):
        return dict(blue=is_blue)
```

Call it in the playbook:

```yaml
---
- hosts: all

  tasks:
    - name: Test custom blue test plugin.
      assert:
        that: "'blue' is blue"
```
