### ISSUE TITLE
Dynamic vars_files inclusion in chapter 5 'Playbook Variables' example broken

### ISSUE THREAD

**Issue by geerlingguy** [geerlingguy/ansible-for-devops#245]
The way that vars_files are included probably changed somewhere in the Ansible 2.x lifecycle, rendering the example in the book a bit broken.

The playbook is:

```yaml
---
- hosts: example
  vars_files:
    - "apache_default.yml"
    - "apache_{{ ansible_os_family }}.yml"
  tasks:
    - service: name={{ apache }} state=running
```

But that doesn't work.

Instead, we used `include_vars` in today's livestream, with `with_first_found`, which worked a bit better. I need to update that example in the book so it works correctly and doesn't mislead readers.

Also `ansible_os_family` is not `CentOS`, it's `RedHat`, on Cent OS (`ansible_distribution` is CentOS, however).

**Comment by geerlingguy** [comment]
New example:

```yaml
---
- hosts: example

  pre_tasks:
    - include_vars: "{{ item }}"
      with_first_found:
        - "apache_{{ ansible_os_family }}.yml"
        - "apache_default.yml"

  tasks:
    - name: Ensure Apache is running.
      service:
        name: "{{ apache_service_name }}"
        state: running
```
