### ISSUE TITLE
Update formatting of code examples (internal)

### ISSUE THREAD

**Issue by geerlingguy** [geerlingguy/ansible-for-devops#246]
I just did this for Ansible for Kubernetes, but I want to do it for Ansible for DevOps just to make sure I'm consistent across both books.

I have code examples formatted like so right now:

```
{lang="text",linenos=off}
    handlers:
      - name: restart apache
        service: name=apache2 state=restarted
    
    tasks:
      - name: Enable Apache rewrite module.
        apache2_module: name=rewrite state=present
        notify: restart apache
```

But I can use the more simplified method in LeanPub's Markua syntax, allowing easier translation between book text and examples/playbooks:

````
{lang="text",linenos=off}
```
handlers:
  - name: restart apache
    service: name=apache2 state=restarted

tasks:
  - name: Enable Apache rewrite module.
    apache2_module: name=rewrite state=present
    notify: restart apache
```
````

Checklist:

- [x] Chapter 1
- [x] Chapter 2
- [x] Chapter 3
- [x] Chapter 4
- [x] Chapter 5
- [x] Chapter 6
- [x] Chapter 7
- [x] Chapter 8
- [x] Chapter 9
- [x] Chapter 10
- [x] Chapter 11
- [x] Chapter 12
- [x] Chapter 13
- [x] Chapter 14
- [x] Appendix A
- [x] Appendix B
