### ISSUE TITLE
Remi's repository (in nodejs examples) isn't necessary

### ISSUE THREAD

**Issue by geerlingguy** [geerlingguy/ansible-for-devops#255]
I'm not sure why it's even in there... but it's not necessary. Node.js still installs at the same version regardless.

**Comment by geerlingguy** [comment]
I have it working in CentOS 8 (on Node.js 10.x) with:

```yaml
---
- hosts: all
  become: yes

  vars:
    node_apps_location: /usr/local/opt/node

  tasks:
    - name: Install EPEL repo.
      yum:
        name: epel-release
        state: present

    - name: Ensure firewalld is stopped (since this is a test server).
      service:
        name: firewalld
        state: stopped

    - name: Install Node.js and npm.
      yum:
        name: npm
        state: present
        enablerepo: epel

    - name: Install Forever (to run our Node.js app).
      npm:
        name: forever
        global: yes
        state: present

    - name: Ensure Node.js app folder exists.
      file:
        path: "{{ node_apps_location }}"
        state: directory

    - name: Copy example Node.js app to server.
      copy:
        src: app
        dest: "{{ node_apps_location }}"

    - name: Install app dependencies defined in package.json.
      npm:
        path: "{{ node_apps_location }}/app"

    - name: Check list of running Node.js apps.
      command: forever list
      register: forever_list
      changed_when: false

    - name: Start example Node.js app.
      command: "forever start {{ node_apps_location }}/app/app.js"
      when: "forever_list.stdout.find(node_apps_location + '/app/app.js') == -1"

```
