### ISSUE TITLE
Use package module instead of chrony

### ISSUE THREAD

**Issue by maxolasersquad** [geerlingguy/ansible-for-devops#270]
In chapter 2 under "Your first Ansible playbook" the following task is performed.

```yml
  - name: Ensure Chrony (for time synchronization) is installed.
    yum:
      name: chrony
      state: present
```

This could also be written like this.
```yml
  - name: Ensure Chrony (for time synchronization) is installed.
    package:
      name: chrony
      state: present
```

This solution is more OS-agnostic and better sells the story that Ansible simplifies infrastructure management by abstracting away details you shouldn't have to worry about. We would now have a playbook that could be run against a wider range of infrastructure that would be truly frustrating to manager with shell scripts
