### ISSUE TITLE
 'unable to prepare context: path "../hello-go" not found'     

### ISSUE THREAD

**Issue by dadav** [geerlingguy/ansible-for-devops#292]
I'm getting the following error while using the hello-go-automation/main.yml playbook:
```yaml
TASK [Build image if it's not already built.] ***************************************************************************************************
fatal: [localhost]: FAILED! => changed=true                                                                                                      
  cmd: |-                                                                                                                                        
    eval $(minikube docker-env)                                                                                                                  
    docker build -t hello-go ../hello-go                                                                                                         
  delta: '0:00:00.423515'                                                                                                                        
  end: '2020-07-05 13:56:05.570495'                                                                                                              
  msg: non-zero return code                                                                                                                      
  rc: 1                                                                                                                                          
  start: '2020-07-05 13:56:05.146980'                                                                                                            
  stderr: 'unable to prepare context: path "../hello-go" not found'                                                                              
  stderr_lines: <omitted>                                                                                                                        
  stdout: ''                                                                                                                                     
  stdout_lines: <omitted>  
```

I could resolve it tho. Just had to change it to `{{ "../hello-go" | realpath }}`.
Maybe my zsh is to blame here? idk

I'm using `ansible 2.9.10` on an archlinux machine.
