### ISSUE TITLE
Chapter 10: Provisioning of Rails app fails

### ISSUE THREAD

**Issue by c3er** [geerlingguy/ansible-for-devops#429]
If I try the example Vagrantfile of the Rails deployment example, it fails at the task "geerlingguy.passenger : Add Phusion apt repo." with the message "apt cache update failed".

Below, an excerpt of the Vagrant/Ansible output. `vagrant up` failed with the same error before. This excerpt also includes a deprecation warning for the task "geerlingguy.nodejs : Add npm_config_prefix bin directory to global $PATH".

```
$ vagrant provision

[...]

TASK [geerlingguy.nodejs : Add npm_config_prefix bin directory to global $PATH.] ***
[DEPRECATION WARNING]: evaluating 'nodejs_generate_etc_profile' as a bare 
variable, this behaviour will go away and you might need to add |bool to the 
expression in the future. Also see CONDITIONAL_BARE_VARS configuration toggle. 
This feature will be removed in version 2.12. Deprecation warnings can be 
disabled by setting deprecation_warnings=False in ansible.cfg.
ok: [default]

[...]

TASK [geerlingguy.passenger : Add Passenger apt key.] **************************
ok: [default]

TASK [geerlingguy.passenger : Add apt HTTPS capabilities.] *********************
ok: [default]

TASK [geerlingguy.passenger : Add Phusion apt repo.] ***************************
fatal: [default]: FAILED! => {"changed": false, "msg": "apt cache update failed"}

PLAY RECAP *********************************************************************
default                    : ok=24   changed=0    unreachable=0    failed=1    skipped=30   rescued=0    ignored=0   

Ansible failed to complete successfully. Any error output should be
visible above. Please fix these errors and try again.
```

My operating system is Ubuntu 20.04
My VirtualBox version is Version 6.1.26

**Comment by matmartin** [comment]
I had the same problem.

See also the issue [Keyserver Timeout](https://github.com/geerlingguy/ansible-role-passenger/issues/18) for the Ansible role **geerlingguy.passenger**.

I have therefore made the following local changes to the **geerlingguy.passenger** role:

```
# Passenger repository setup.
- name: Add Passenger apt key.
  apt_key:
    keyserver: hkp://keyserver.ubuntu.com:80
    id: 561F9B9CAC40B2F7
    state: present

- name: Update ca-certificates package.
  apt: name=ca-certificates state=latest update_cache=yes

- name: Add apt HTTPS capabilities.
  apt: name=apt-transport-https state=present
```

After modifying the keyserver and adding the task to update the ca-certificates package, it worked again.
