### ISSUE TITLE
Chapter 4 - REMI gpg key request failed

### ISSUE THREAD

**Issue by mikerossiter** [geerlingguy/ansible-for-devops#452]
`fatal: [default]: FAILED! => {"changed": false, "msg": "failed to fetch key at https://rpms.remirepo.net/RPM-GPG-KEY-remi , error was: Request failed: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:618)>"}`

Hi. I'm having trouble with chapter 4. I have the book  and cloned the repo. I did a `vagrant up` on the nodejs folder. I had to change the IP address for the VM as it was complaining. Then this happened when it started to provision it. I SSHed to the box and it has network access and I can update it but even if I replace the key (not that I needed to) it still won't work. 

Please help! I also tried another folder and I still had the same issue once the box starting provisioning. I'm sure there's a simple answer. Thanks in advance.

**Comment by geerlingguy** [comment]
Hmm... that one's using my CentOS 7 box, and typically if there's an SSL error that either means the VM needs to run some updates to get the latest certs, or something else in the chain could be causing the certificate to not be valid (either the remi repo server is outdated — but I just tested https://rpms.remirepo.net/RPM-GPG-KEY-remi and it's fine, or something else might not be validating the cert in CentOS 7.

**Comment by Trojanekkk** [comment]
In my case centos VM also cannot verify SSL certificate. The easiest (and obviously insecure) solution is to modify playbook and change https => http at erroneous lines. Then everything works fine.

**Comment by meysiolio** [comment]
I had the same problem with the Remi GPG key and rpm file. Seems the links cannot be evaluated on the new server using ansible. I worked around the problem by copying the GPG and RPM file on each target server, which obviously is not an ideal solution:
```
  tasks:
    - name: Copy Remi repo files.
      copy: "src=remi-repo dest=~"

    - name: Install EPEL repo.
      yum: name=epel-release state=present

    - name: Import Remi GPG key.
      rpm_key:
        key: /root/remi-repo/RPM-GPG-KEY-remi
        state: present

    - name: Install Remi repo.
      yum:
        name: /root/remi-repo/remi-release-7.rpm
        state: present
```
