### ISSUE TITLE
first-ansible-playbook fails

### ISSUE THREAD

**Issue by DonBower** [geerlingguy/ansible-for-devops#465]
I am extrapolating from your playbook.yaml file, trying to add a couple more tasks.
My playbook.yaml:
```
---
- name: Update APT Cache
  hosts: k8svm
  connection: local
  debugger: on_failed
  # connection: ansible.netcommon.network_cli
  gather_facts: no
  remote_user: don
  become: yes

  tasks:
    - name: Upgrade installed APT Packages
      ansible.builtin.apt:
        upgrade: yes
        update_cache: yes

    - name: Install APT Packages
      ansible.builtin.apt:
        pkg:
        - net-tools
        - dnsutils
        - python-is-python3
        - python3-pip
        - wget
        - jq
        state: present

    # - name: Ensure docker is running
    #   service:
    #     name: docker
    #     state: started
    #     enabled: yes

    - name: Ensure kublet is running
      service:
        name: kublet
        state: started
        enabled: yes
```
I can't get either task to pass, they both seem to fail with the same error:
```
fatal: [k8s-vm1.ag6hq.net]: FAILED! => {"changed": false, "msg": "Could not find the requested service docker: host"}
```
or
```
fatal: [k8s-vm1.ag6hq.net]: FAILED! => {"changed": false, "msg": "Could not find the requested service kublet: host"}
```

my environment is:
2 ESXi VMs running Ubuntu 20.04.  They both have docker and kublet currently running. I can run the `systemctl status docker` or `systemctl status kublet` with positive results.
1 Raspberry Pi 4 with default Raspberry Pi OS  and `ansible --version = ansible [core 2.12.2]`
Inventory file:
```
---
k8svm:
  # ansible_network_os: linux
  # ansible_user: don
  # ansible_become_user: root

  hosts:
    k8s-vm0.ag6hq.net:
      ansible_python_interpreter: /usr/bin/python
    k8s-vm1.ag6hq.net:
      ansible_python_interpreter: /usr/bin/python
```
Execution script:
```
#!/bin/bash
clear
echo $0 $@

if [[ -f $1 ]]; then
    ansibleBecome="--become-password-file $1"
  else
    ansibleBecome="--ask-become-pass"
fi

if [[ $DEBUG -gt 0 ]]; then
  echo -e "ansible-playbook \\"
  echo -e "  --inventory-file hosts.yaml \\"
  echo -e "  --connection ansible.netcommon.network_cli \\"
  echo -e "  --user don \\"
  echo -e "  ${ansibleBecome} \\"
  echo -e "  update.yaml"
fi

ansible-playbook \
  --inventory-file hosts.yaml \
  --connection ansible.netcommon.network_cli \
  --user don \
  ${ansibleBecome} \
  update.yaml
```

I am sure I have some syntax wrong somewhere, but I can't seem to figure it out.

**Comment by DonBower** [comment]
It appears this syntax variant will work:
```
  tasks:
    - name: Ensure services are started
      become: yes
      ansible.builtin.systemd:
        name: "{{item}}"
        state: started
      with_items:
        - "docker"
        - "kubelet"
```

I'll drop a issue in ansible/ansible.

**Comment by DonBower** [comment]
p.s.
this works as well:
```
   - name: Ensure docker is started
      become: yes
      ansible.builtin.systemd:
        service: docker
        state: started
```
notice using "`service:`" instead of "`name:`"
