### ISSUE TITLE
Chapter 15 - page 403 - db snippet missing 'command'

### ISSUE THREAD

**Issue by hubertbanas** [geerlingguy/ansible-for-devops#498]
Book version: 2.1
Date as of last publication: April 15, 2022

On page 404 we can ready

>... for the db container, we have two special options: the volumes_from option, which mounts volumes from the specified container (in this case, the data container), and the command, which calls a shell script to start MySQL.

Snippet on page 403 is missing `command` that is being mentioned.

``` yaml
- name: Run a MySQL container.
  docker_container:
    image: db:latest
    name: db
    state: started
    volumes_from: data
    ports: "3306:3306"
    env:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: flask
      MYSQL_USER: flask
      MYSQL_PASSWORD: flask
```
