### ISSUE TITLE
Chapter 4 Solr - Site cant be reached

### ISSUE THREAD

**Issue by MrRoyce** [geerlingguy/ansible-for-devops#523]
Hey there - I ran the playbook, everything is loaded and looks ok, but I cant bring up solr in Chrome.

I tried 192.168.60.5:8983/solr and a few other URL's but I get `ERR_CONNECTION_REFUSED`

I am able to access the a site in the browser for a simple Nginx application that I wrote with Ansible so I think everything is setup correctly but solr is not working for me.

Any help is appreciated

**Comment by voegelas** [comment]
In my case Solr was only listening on the loopback interface and thus could not be reached from the outside. I added a task that edits `/etc/default/solr.in.sh` to the playbook (see voegelas/ansible-for-devops@08fc9946ec002fd6f8df2c2c8c1e7e741d5510be).

```yaml
    - name: Accept connections on all network interfaces.
      lineinfile:
        dest: "/etc/default/solr.in.sh"
        regexp: "^#SOLR_JETTY_HOST="
        line: 'SOLR_JETTY_HOST="0.0.0.0"'
        state: present
```

You can investigate such problems by entering the virtual machine with `vagrant ssh` and running `sudo ss -tnlp`, for example.
