### ISSUE TITLE
forever list fails : [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by pixeline** [geerlingguy/ansible-for-devops#85]
Using Ansible 2.4.2.0; Darwin

When running the [nodejs provisioning playbook](https://github.com/geerlingguy/ansible-for-devops/blob/master/nodejs/provisioning/playbook.yml#L28-L47), it keeps failing when it reaches this task:

https://github.com/geerlingguy/ansible-for-devops/blob/ed1f0325bab17b9115b355403b9579e68634de66/nodejs/provisioning/playbook.yml#L40

The error message :

```shell
[Errno 2] No such file or directory
fatal: [domain.com]: FAILED! => {"changed": false, "cmd": "forever list", "rc": 2}
```

The full task:

```yml
- name: "Check list of running Node.js apps."
  command: forever list
  register: forever_list
  changed_when: false
``` 

I've triple-checked that the app.js file is there. Why does it not find it ?
