### ISSUE TITLE
Update all examples to assume Python 3 by default

### ISSUE THREAD

**Issue by ss10sb** [geerlingguy/ansible-for-devops#93]
I think it might be worth adding a blurb early on (maybe in the 'creating a basic inventory file' part) about setting ansible to use python 3 by default (for distros that no longer come with 2.7).

For [example], it could be as simple as mentioning you can add a couple of lines to the inventory file like:
[example:vars]
ansible_python_interpreter=/usr/bin/python3

Or even directly to the host line.  Just to get things started and not fail immediately on the ping example :)

**Comment by geerlingguy** [comment]
@ss10sb - Good idea! Right now the only OSes where this is a concern are Ubuntu 16 and 18... but it will become more and more important.

I think I'll add a note/warning in there about it. Hopefully Ansible itself will eventually get more intelligent about detecting Python 3 installed on a system :/

See related issue upstream: https://github.com/ansible/ansible/issues/26163

**Comment by geerlingguy** [comment]
It's now an issue on Debian 10, which includes Python 3 as the default (though I think it aliases `python` to `python3`...? Not sure about `pip`).

So yes, I think at some point I'm going to try to figure out how to introduce this a little more gently. Otherwise, I wonder if support is now better, as according to the docs, Ansible will automatically use python3 on certain managed OSes... https://docs.ansible.com/ansible/latest/reference_appendices/python_3_support.html

I'll have to do some testing to see if I still need to do my hacky hack:

```
  pre_tasks:
    - name: Install Python if not already present.
      raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)
      changed_when: false

    - name: Gather facts after Python is definitely present.
      setup:
```
